import type { Position, TransactionRecord } from '@/types/portfolio';
import type { AppNotification } from '@/types/notification';
import type { PageView } from '@/types/navigation';
import type { User } from 'firebase/auth';

export interface DashboardViewProps {
  user: User | null;
  positions: Position[];
  filledPositions: Position[];
  transactions: TransactionRecord[];
  fxRates: Record<string, number>;
  totalValue: number;
  totalCost: number;
  bourseVal: number;
  bourseCostVal: number;
  cryptoVal: number;
  cryptoCostVal: number;
  savingsVal: number;
  savingsCostVal: number;
  savingsAnnualInt: number;
  monthlyDCATotal: number;
  bourseDCAVal: number;
  cryptoDCAVal: number;
  savingsDCAVal: number;
  dcaBreakdown: any;
  notifications: AppNotification[];
  pendingCount: number;
  marketStatusLabel?: string;
  lastPricesUpdated: number | null;
  dcaGlobalStartDate: string;
  handleUpdateDcaStartDate: (dateStr: string) => void;
  adjustInflation: boolean;
  inflationRate: number;
  peaSeniority: 'under5' | 'over5';
  netLiquidationDetails: any;
  showTotalValueDropdown: boolean;
  setShowTotalValueDropdown: (v: boolean) => void;
  showTotalCostDropdown: boolean;
  setShowTotalCostDropdown: (v: boolean) => void;
  showGainLossDropdown: boolean;
  setShowGainLossDropdown: (v: boolean) => void;
  showDcaFrequencyDropdown: boolean;
  setShowDcaFrequencyDropdown: (v: boolean) => void;
  queryInput: string;
  setQueryInput: (q: string) => void;
  isRunning: boolean;
  handleRunAnalysis: (flag?: boolean) => void;
  refreshingPrices: boolean;
  setRefreshingPrices: (r: boolean) => void;
  showToast: (msg: string, type?: 'success' | 'error') => void;
  openGlossary: (term: string) => void;
  openRebalanceModal: () => void;
  setShowIntegrationsModal: (v: boolean) => void;
  setRebalanceBudgetMode: (mode: any) => void;
  setFlowRebalanceResult: (res: any) => void;
  setShowFlowRebalanceModal: (v: boolean) => void;
  setShowNotificationModal: (v: boolean) => void;
  setShowNetDetailsModal: (v: boolean) => void;
  setShowConfigEditor: (v: boolean) => void;
  setShowThemeInfoModal: (v: boolean) => void;
  setShowTransactionModal: (v: boolean) => void;
  setSelectedHistoryTicker: (ticker: string | undefined) => void;
  setEditingPosition: (pos: Position | null | 'new' | 'new_savings' | 'new_crypto') => void;
  handleDeletePosition: (id: string) => void;
  handleSavePosition: (pos: Position) => Promise<void>;
  upsertPositionsBatch: (batch: Position[]) => Promise<void>;
  refreshSavingsPrices: () => Promise<any>;
  refreshMarketPrices: () => Promise<any>;
  refreshCryptoPrices: (v?: boolean) => Promise<any>;
  resetPortfolio: () => Promise<void>;
  updatePosition: (pos: Position, customReason?: string) => Promise<void>;
  addPosition: (pos: Position) => Promise<void>;
  undoLastAction: () => any;
  redoLastAction: () => any;
  canUndo: boolean;
  canRedo: boolean;
  saving: boolean;
  onNavigateView: (view: PageView) => void;
}
