import type { Position, PortfolioConfig } from '@/types/portfolio';
import type { PageView } from '@/types/navigation';

export interface PortfolioModalsContainerProps {
  editingPosition: Position | 'new' | 'new_savings' | 'new_crypto' | null;
  setEditingPosition: (pos: Position | 'new' | 'new_savings' | 'new_crypto' | null) => void;
  positions: Position[];
  handleSavePosition: (pos: Position) => void | Promise<void>;
  handleDeletePosition: (id: string) => void | Promise<void>;
  showConfigEditor: boolean;
  setShowConfigEditor: (show: boolean) => void;
  config: PortfolioConfig | null;
  investorProfile: any;
  handleSaveConfig: (cfg: PortfolioConfig) => void | Promise<void>;
  updateInvestorProfile: (profile: any) => void | Promise<void>;
  handleTestNotification: () => void | Promise<void>;
  handleTestEmail: () => void | Promise<void>;
  showFlowRebalanceModal: boolean;
  setShowFlowRebalanceModal: (show: boolean) => void;
  flowRebalanceResult: any;
  setFlowRebalanceResult: (res: any) => void;
  rebalanceBudgetMode: 'dca' | 'tampon' | 'extra' | 'combo' | 'custom';
  setRebalanceBudgetMode: (mode: 'dca' | 'tampon' | 'extra' | 'combo' | 'custom') => void;
  customRebalanceAmount: number;
  setCustomRebalanceAmount: (amt: number) => void;
  fxRates: Record<string, number>;
  boursoLive: any;
  totalAvailableExtraCash: number;
  extraCashEntries: any[];
  saveExtraCashEntry: (entry: any) => Promise<void>;
  updatePosition: (pos: Position, customReason?: string) => Promise<void>;
  clearAnalysisCache: () => void;
  setReadNotificationIds: (ids: string[]) => void;
  setClearedNotificationIds: React.Dispatch<React.SetStateAction<string[]>>;
  notifications: any[];
  showToast: (msg: string, type?: 'success' | 'error') => void;
  showProfileModal: boolean;
  setShowProfileModal: (show: boolean) => void;
  user: any;
  setShowEditProfile: (show: boolean) => void;
  signOut: () => void | Promise<void>;
  showNotificationModal: boolean;
  setShowNotificationModal: (show: boolean) => void;
  notificationSettings: any;
  setNotificationSettings: (settings: any) => void;
  handleDirectAnalysis: (query: string) => void;
  setCurrentView: (view: PageView) => void;
  openRebalanceModal: () => void;
  activeProxyModalAsset: any;
  setActiveProxyModalAsset: (asset: any) => void;
  showThemeInfoModal: boolean;
  setShowThemeInfoModal: (show: boolean) => void;
  showGlossaryModal: boolean;
  setShowGlossaryModal: (show: boolean) => void;
  glossaryInitialTerm?: string;
  showMonteCarloModal: boolean;
  setShowMonteCarloModal: (show: boolean) => void;
  totalValue: number;
  monthlyDCATotal: number;
  showIntegrationsModal: boolean;
  setShowIntegrationsModal: (show: boolean) => void;
  showTransactionModal: boolean;
  setShowTransactionModal: (show: boolean) => void;
  transactions: any[];
  selectedHistoryTicker?: string;
  showNetDetailsModal: boolean;
  setShowNetDetailsModal: (show: boolean) => void;
  netLiquidationDetails: any;
  peaSeniority: 'under5' | 'over5';
  setPeaSeniority: (val: 'under5' | 'over5') => void;
}
